# Set to true if debug messages should be enabled (warning: this can spam the console)
debug: true

# How much space should be left below each line of a hologram.
spacing:
  # The amount of space (Y axis) that should be the margin for text lines.
  text:
    top: 0.1
    bottom: 0.2
  # The amount of space (Y axis) that should be the margin for item lines.
  item:
    top: 0.5
    bottom: 0.4